### ISSUE TITLE
Enhancement Ender Battery

### ISSUE THREAD

**Issue by AbsorbingSafe11** [trunksbomb/Batteries#1]
Basic Concept:
Wireless charging of linked Ender Batteries.
Advanced Description:
A player would craft two batteries (just one would still function as normal battery) link the two batteries and place one in a charger, then the second battery would be in the player's inventory and receive the same charge from the first battery.
(that way wireless charging without adding any blocks and balanced at most tiers of player advancement)
Secondary Concept:
An enderchest style charger that received power from other tech mods and could have a linked pouch that stored and charged batteries.

**Comment by trunksbomb** [comment]
I think the best way to about this will be:
- Add the charging station/block (I had already planned on adding this)
- Add an Ender battery, which will be an Ultimate Battery + some extra cost (+ender pearls)
- Add a variant of the charging station that costs more (+ender pearls) that takes a reference of your Ender Battery (doesn't actually store it, just like how the battery only has ghost copies/reference to the item)
- When the Ender charging station receives energy, send it to the battery in your inventory

I'll leave chunk loading to another mod as there are plenty of mods with chunk loading capabilities already.

**Comment by AbsorbingSafe11** [comment]
Looking forward to how this is implemented. (looks really cool and useful)
As a small suggestion, the variant of the charger should be cheaper and more easily accessed by players, since it would require a chunkloader for full use. (maybe the ender battery could require endstone to gate progression)

**Comment by trunksbomb** [comment]
Implementation done, just got to work out a few kinks and it'll be ready for upload.

![batteries_ender](https://user-images.githubusercontent.com/1904331/102003428-595e8780-3cd5-11eb-9ced-87e764d978b0.gif)

**Comment by trunksbomb** [comment]
https://www.curseforge.com/minecraft/mc-mods/batteries/files/3137548 Released

Thanks again for the suggestion.
